### PR TITLE
Feature schema

### PR DESCRIPTION
**Pull request by nstrain**
A basic schema and example table for our habit buddy project. This pull request incorporates the suggestions we received in lab on Friday.

### CODE REVIEW

**Review by kny4 — APPROVED** [review]
The tables look good! I guess we should make sure they align with whatever I'm gonna put in the domain model hahaha
So, the categories I'm seeing are:
- school
- exercise
- leisure
Joe has a "spiritual" category that I like too and I think the four are a good number.

I'm a little confused on whether or not there will should be different tables for the user account and user profile. Right now in the UML model, I have to separate classes, but I don't really know if that's necessary. The two are different now, but the distinctions aren't huge.

**Review by kny4 — APPROVED** [review]

**Review by andrewJamesBaker — CHANGES_REQUESTED** [review]
So I am going to push my current queries file to a new branch soon and it might be wise to look it over and see what does and does not line up. Most of what I have written up is just comments prepping for when the schema is done, so there is very little actual code. 

A couple of things I would suggest: 

Look at Kelsey's UML domain model. I feel like it should line up a d little more than it does at the moment. Your table should have some details about the actual first and last name, and also URL (so varchar) picture data.

 Also as Kelsey has suggested, please as spiritual to the HabitCategories.

Lastly, if you could comment on your code to give a little more explanation for it, I would appreciate it as I continue to write queries. At the moment I don't really understand why the habit categories were broken up into three tables (this seems a little unnecessary to me) and I think much of this can be condensed into the four tables that Kelsey has in her diagram. I could be very wrong about this, so I would like some explanation. 

To end on a more positive note, good work so far. The database side is hard figuring out what needs to be where. Thank you for your willingness to tackle the back end.

**Review by Bongo9911 — CHANGES_REQUESTED** [review]
- Username table should probably be renamed to User table
- UserHabit table is unnecessary, should instead just put the UserId with each habit in the Habit table since each habit is unique to a user
- UserBuddy table doesn’t need a primary key
- UserBuddy table needs some way of referencing both user’s habits (maybe by referencing the category of the habits they’re taking up?)

**Comment by kny4** [comment]
To be fair, I probably have too many things in my uml model hahaha

**Review by kny4 — APPROVED** [review]
It looks good to me! I think I still don't understand the multiplicity (or at least how to write it on the uml model), but this has nothing to do with the schema and everything to do with my ignorance hahaha

**Review by Bongo9911 — CHANGES_REQUESTED** [review]
The Habit table is missing a reference to the id of the user who holds the habit. Without that, we don't know what habits the user holds.

**Comment by Bongo9911** [comment]
Also, could we get these fields in the User table:
- Notifications: Boolean
- Theme: VarChar (Currently 'Light' or 'Dark')

**Review by Bongo9911 — CHANGES_REQUESTED** [review]
Line 43 says "buddyHabitID"
Line 44 says "buddy1habitID"

should switch line 44 to use the same as line 43

**Pull request merged**
